### PR TITLE
Add LuukDAO profile with new image without spacing

### PR DESCRIPTION
**Pull request by LuukDAO**

### CODE REVIEW

**Review by aaronmgdr — DISMISSED** [review]

**Comment by aaronmgdr** [comment]
@LuukDAO approved but you will need to fix the prettier lint issue before we can merge

**Comment by LuukDAO** [comment]
> @LuukDAO approved but you will need to fix the prettier lint issue before we can merge

Can you articulate what I should do to fix this issue? I believe you're allowed to overwrite my request? If so - can you fix it for me?

**Comment by LuukDAO** [comment]
Hey @aaronmgdr please let me know what I should change

**Comment by aaronmgdr** [comment]
hey @LuukDAO 

my apologiese the short answer is to run `yarn prettier`. and commit the changes. but that assumes you pulled the repo and made the changes locally. 

the better answer is that that would show you something like below (you need to add a space after Public Good and before SuperChain.) 

[Working on automating this](https://github.com/celo-org/celo-mondo/pull/31) because the experience sucks for all currently

```diff
-"interests": ["ReFi", "Stablecoins", "DeFi", "Public Goods","Superchain"],
+"interests": ["ReFi", "Stablecoins", "DeFi", "Public Goods", "Superchain"],
```

**Review by aaronmgdr — APPROVED** [review]

**Pull request merged**
